version: "3.8"

services:
  php-fpm:
    container_name: main-php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - /var/www/vendor/
      - ./../:/var/www/
    ports:
      - ${NGINX_HOST_HTTP_PORT}:8080
    networks:
        - sail

  mailpit:
      image: 'axllent/mailpit:latest'
      ports:
          - '${FORWARD_MAILPIT_PORT:-1025}:1025'
          - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
      networks:
          - sail
networks:
    sail:
        driver: bridge
